<a href="https://colab.research.google.com/github/pavanraja753/PyTorch_Learning/blob/main/Fundamentals_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Contents


1. Installation
2. Initialization
3. Accessing and modifying data
4. Pivoting data
5. Combining data
6. Math operations



## 1. Installation

Generally NumPy is pre-installed on Colab.AWS. you should first check if NumPy is available

In [2]:
# Import the Numpy
import numpy as np

np.random.seed(0)

# 2. Initialization

In [11]:
# Initailzes an empty array with size 2 x 2
empty_arr = np.empty((2,2))

print("An empty array is \n", empty_arr, "with dimension ", empty_arr.shape, "\n")

zeros_arr = np.zeros((2,3))

print("An zeros array is \n", zeros_arr, "with dimension ", zeros_arr.shape, "\n")

ones_arr = np.ones((4,2))
print("An ones array is \n", ones_arr, "with dimension ", ones_arr.shape, "\n")

tens_arr = np.full((2,2),10)
print("A filled array is \n", tens_arr, "with dimension ", tens_arr.shape, "\n")

zeros_like_arr = np.zeros_like(ones_arr)
print("A zeros like array is \n", zeros_like_arr, "with dimension ", zeros_like_arr.shape, "\n")

full_like_arr = np.full_like(zeros_arr, 0.1, dtype=np.double)
print("A full like array is \n", full_like_arr, "with dimension ", full_like_arr.shape, "\n")





An empty array is 
 [[5.e-323 5.e-323]
 [5.e-323 5.e-323]] with dimension  (2, 2) 

An zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]] with dimension  (2, 3) 

An ones array is 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] with dimension  (4, 2) 

A filled array is 
 [[10 10]
 [10 10]] with dimension  (2, 2) 

A zeros like array is 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] with dimension  (4, 2) 

A full like array is 
 [[0.1 0.1 0.1]
 [0.1 0.1 0.1]] with dimension  (2, 3) 



###b. Create an array from existing data

In [12]:
# initialize an array with the given list

new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print("An array from given list is \n", arr_from_list, "with dimensions", arr_from_list.shape, "\n")

An array from given list is 
 [1 2 3 4] with dimensions (4,) 



In [ ]:
# initialized an arrat by loading data from a txt file
txt_arr = np.loadtxt(path_to_txt_file)

# initialize an array by loading data from a npy file
loaded_arr = np.load(path_to_npy_file)


###c. Numerical ranges

In [15]:
# return evenly spaced values within a given interval
range_arr = np.arange(10)
print("An array given range is \n", range_arr, "with dimensions", range_arr.shape, "\n")

# return evenly spaced numbers over a specified interval
linspace_arr = np.linspace(2.0,3.0,num=5, endpoint=True)
print("An evenly space array given range is \n", linspace_arr, "with dimensions", linspace_arr.shape, "\n")


An array given range is 
 [0 1 2 3 4 5 6 7 8 9] with dimensions (10,) 

An evenly space array given range is 
 [2.   2.25 2.5  2.75 3.  ] with dimensions (5,) 



###d. Create an array with random values

In [19]:
uniform_rand_arr = np.random.rand(3,2)
print("An random array given range is \n", uniform_rand_arr, "with dimensions", uniform_rand_arr.shape, "\n")

range_rand_int_arr = np.random.randint(5,size=(2,4))
print(range_rand_int_arr)

mu =3
sigma = 2.5
sample_norm_arr = mu + sigma*np.random.randn(2,4)

print(sample_norm_arr)

An random array given range is 
 [[0.83261985 0.77815675]
 [0.87001215 0.97861834]
 [0.79915856 0.46147936]] with dimensions (3, 2) 

[[3 3 0 1]
 [1 1 0 2]]
[[-0.90874173  1.58325595  2.39462621  6.78597821]
 [ 2.1673565   3.11841204  6.65685112  6.83757282]]


[[0 1 1 0]
 [1 4 3 0]]
