<a href="https://colab.research.google.com/github/pavanraja753/PyTorch_Learning/blob/main/Fundamentals_of_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction

1. PyTorch is an open-source deep learning framework

2. Major components

  1. PyTorch Tensors
  2. NN Module
  3. Optim Module
  4. Autograd module

3. How do I install PyTorch

  1. pip3 install torch torchvision
  2. conda install pytorch torchvision -c pytorch

# Contents

1. Introduction
2. Contents
3. PyTorch Tensors

In [1]:
import torch
torch.manual_seed(0)

In [2]:
# Creating tensorrs without data

t1 = torch.ones(size=(5,3))
t2 = torch.zeros(size=(5,3))
t3 = torch.eye(3)
t4 = torch.rand(size=(3,4))
t5 = torch.arange(7)

print(t1)
print(t2)
print(t3)
print(t4)
print(t5)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([0, 1, 2, 3, 4, 5, 6])


In [4]:
# Creating tensors from existing data (most common cases)

import numpy as np

t1 = torch.tensor([1,2,3,4]) # from numpy list
t2 = torch.tensor(np.array([1,2,3,4])) # from numpy array
t3 = torch.tensor(np.random.randn(3))  # from numpy array
t4 = t3.clone().detach() # from existing torch tensor

# creating the copy of a Torch tensor

print(t1)
print(t2)
print(t3)
print(t4)

tensor([1, 2, 3, 4])
tensor([1, 2, 3, 4])
tensor([-0.3367, -0.8957, -1.2319], dtype=torch.float64)
tensor([-0.3367, -0.8957, -1.2319], dtype=torch.float64)


In [5]:
# Converting tensor to numpy array

t1 = torch.tensor([1,2,3,4])
t2 = t1.detach().numpy()

print('Tensor',t1)
print('Numpy',t2)

Tensor tensor([1, 2, 3, 4])
Numpy [1 2 3 4]


## Accessing Tensors

**Note:** Tensor values can easily be modified by using the accessing method to select the desired selection of the tensor to be modified

In [12]:
# Basic

t = torch.rand(size=(3,4,5))

print('Original Tensor t:')
print(t)
print('\n')

# Some valid ways of accessing individual elemets in the tensor
print('t[0][0][0]\n',t[0][0][0])
print('t[1,2,3]\n',t[1,2,3])
print('t[1,2][3]\n',t[1,2][3])

# Tensor Slicing

print('t[0]\n', t[0])
print('t[:1]\n', t[:1])
print('t[:,1]\n',t[:,1])
print('t[:,:,3]\n',t[:,:,3])

Original Tensor t:
tensor([[[0.1220, 0.2560, 0.0170, 0.2161, 0.9112],
         [0.9094, 0.8579, 0.8861, 0.9446, 0.3720],
         [0.7200, 0.9455, 0.6654, 0.9998, 0.7593],
         [0.8108, 0.3250, 0.7399, 0.5575, 0.3806]],

        [[0.2181, 0.2194, 0.1153, 0.8357, 0.8555],
         [0.4431, 0.2107, 0.8865, 0.8197, 0.5372],
         [0.2639, 0.9595, 0.7045, 0.1204, 0.9785],
         [0.8797, 0.3178, 0.7811, 0.2159, 0.4216]],

        [[0.9246, 0.5207, 0.1464, 0.3329, 0.3643],
         [0.4035, 0.5479, 0.9624, 0.5268, 0.1913],
         [0.5256, 0.7397, 0.7480, 0.0430, 0.4105],
         [0.1284, 0.2867, 0.6801, 0.1449, 0.6859]]])


t[0][0][0]
 tensor(0.1220)
t[1,2,3]
 tensor(0.1204)
t[1,2][3]
 tensor(0.1204)
t[0]
 tensor([[0.1220, 0.2560, 0.0170, 0.2161, 0.9112],
        [0.9094, 0.8579, 0.8861, 0.9446, 0.3720],
        [0.7200, 0.9455, 0.6654, 0.9998, 0.7593],
        [0.8108, 0.3250, 0.7399, 0.5575, 0.3806]])
t[:1]
 tensor([[[0.1220, 0.2560, 0.0170, 0.2161, 0.9112],
         [0.9094, 

## Pivoting and Reshaping Tensors

1. Flatten
2. Squeeze
3. Reshape
4. View
5. Transpose
6. Permute

**Important stuff**


In [13]:
# Flatten a tensor

# Flatten the entire tensor. Elements are exhausted in the last dimension first when flattening 1.e t[0,0,0] is followed by t[0,0,1] and so on
print(t)
print(t.flatten())

tensor([[[0.1220, 0.2560, 0.0170, 0.2161, 0.9112],
         [0.9094, 0.8579, 0.8861, 0.9446, 0.3720],
         [0.7200, 0.9455, 0.6654, 0.9998, 0.7593],
         [0.8108, 0.3250, 0.7399, 0.5575, 0.3806]],

        [[0.2181, 0.2194, 0.1153, 0.8357, 0.8555],
         [0.4431, 0.2107, 0.8865, 0.8197, 0.5372],
         [0.2639, 0.9595, 0.7045, 0.1204, 0.9785],
         [0.8797, 0.3178, 0.7811, 0.2159, 0.4216]],

        [[0.9246, 0.5207, 0.1464, 0.3329, 0.3643],
         [0.4035, 0.5479, 0.9624, 0.5268, 0.1913],
         [0.5256, 0.7397, 0.7480, 0.0430, 0.4105],
         [0.1284, 0.2867, 0.6801, 0.1449, 0.6859]]])
tensor([0.1220, 0.2560, 0.0170, 0.2161, 0.9112, 0.9094, 0.8579, 0.8861, 0.9446,
        0.3720, 0.7200, 0.9455, 0.6654, 0.9998, 0.7593, 0.8108, 0.3250, 0.7399,
        0.5575, 0.3806, 0.2181, 0.2194, 0.1153, 0.8357, 0.8555, 0.4431, 0.2107,
        0.8865, 0.8197, 0.5372, 0.2639, 0.9595, 0.7045, 0.1204, 0.9785, 0.8797,
        0.3178, 0.7811, 0.2159, 0.4216, 0.9246, 0.5207, 0.1464

In [ ]:
# Squeeze and Unsqueeze tensors
# Unsqueeze and squeeze are very handy commands to add and remove a dimension from the tensor

ts = t.unsqueeze(0)
ts2 = t.unsqueeze(1)

print(t)
print(t.shape)
print(ts)
print(ts.shape)

print(ts2)
print(ts2.shape)

print(ts.squeeze(3))  

In [20]:
# Reshape tensor

print(t.reshape(12,5))
print(t.reshape(12,-1))
print(t.reshape(5,4,3))
print(t.reshape(-1))

# View also does the similar thing, but we dont have to use this

tensor([[0.1220, 0.2560, 0.0170, 0.2161, 0.9112],
        [0.9094, 0.8579, 0.8861, 0.9446, 0.3720],
        [0.7200, 0.9455, 0.6654, 0.9998, 0.7593],
        [0.8108, 0.3250, 0.7399, 0.5575, 0.3806],
        [0.2181, 0.2194, 0.1153, 0.8357, 0.8555],
        [0.4431, 0.2107, 0.8865, 0.8197, 0.5372],
        [0.2639, 0.9595, 0.7045, 0.1204, 0.9785],
        [0.8797, 0.3178, 0.7811, 0.2159, 0.4216],
        [0.9246, 0.5207, 0.1464, 0.3329, 0.3643],
        [0.4035, 0.5479, 0.9624, 0.5268, 0.1913],
        [0.5256, 0.7397, 0.7480, 0.0430, 0.4105],
        [0.1284, 0.2867, 0.6801, 0.1449, 0.6859]])
tensor([[0.1220, 0.2560, 0.0170, 0.2161, 0.9112],
        [0.9094, 0.8579, 0.8861, 0.9446, 0.3720],
        [0.7200, 0.9455, 0.6654, 0.9998, 0.7593],
        [0.8108, 0.3250, 0.7399, 0.5575, 0.3806],
        [0.2181, 0.2194, 0.1153, 0.8357, 0.8555],
        [0.4431, 0.2107, 0.8865, 0.8197, 0.5372],
        [0.2639, 0.9595, 0.7045, 0.1204, 0.9785],
        [0.8797, 0.3178, 0.7811, 0.2159, 0.4216],

In [26]:
# Transpose Tensor
# This operation is primarly a generalization of the regular matrix transopse


# Can be only between two axis

t = torch.tensor([[[1,2,3,4],[5,6,7,8],[0,10,11,12]],[[-1,-2,-3,-4],[-5,-6,-7,-8],[-9,-10,-11,-12]]])
print(t.shape)
print(t)
print('\n')

print(t.transpose(0,1).shape)
print(t.transpose(0,1))
print('\n')

print(t.transpose(0,2).shape)
print(t.transpose(0,2))
print('\n')

torch.Size([2, 3, 4])
tensor([[[  1,   2,   3,   4],
         [  5,   6,   7,   8],
         [  0,  10,  11,  12]],

        [[ -1,  -2,  -3,  -4],
         [ -5,  -6,  -7,  -8],
         [ -9, -10, -11, -12]]])


torch.Size([3, 2, 4])
tensor([[[  1,   2,   3,   4],
         [ -1,  -2,  -3,  -4]],

        [[  5,   6,   7,   8],
         [ -5,  -6,  -7,  -8]],

        [[  0,  10,  11,  12],
         [ -9, -10, -11, -12]]])


torch.Size([4, 3, 2])
tensor([[[  1,  -1],
         [  5,  -5],
         [  0,  -9]],

        [[  2,  -2],
         [  6,  -6],
         [ 10, -10]],

        [[  3,  -3],
         [  7,  -7],
         [ 11, -11]],

        [[  4,  -4],
         [  8,  -8],
         [ 12, -12]]])




In [29]:
# Permute tensor
# This operation allows the used to simultaneoly reorderd multiple dimensions unlike trnaspose which interchanges two dimensions only

t = torch.tensor([[[1,2,3,4],[5,6,7,8],[0,10,11,12]],[[-1,-2,-3,-4],[-5,-6,-7,-8],[-9,-10,-11,-12]]])
print(t.shape)
print(t)
print('\n')

print(t.permute(1,0,2).shape)
print(t.permute(1,0,2))
print('\n')


torch.Size([2, 3, 4])
tensor([[[  1,   2,   3,   4],
         [  5,   6,   7,   8],
         [  0,  10,  11,  12]],

        [[ -1,  -2,  -3,  -4],
         [ -5,  -6,  -7,  -8],
         [ -9, -10, -11, -12]]])


torch.Size([3, 2, 4])
tensor([[[  1,   2,   3,   4],
         [ -1,  -2,  -3,  -4]],

        [[  5,   6,   7,   8],
         [ -5,  -6,  -7,  -8]],

        [[  0,  10,  11,  12],
         [ -9, -10, -11, -12]]])




# Why Numpy

- Lists are designed to store heterogenous data
- No low-level hardware mechanisms to accelerate operations on lists
- Most Processors involve vectorization

This is why Numpy

- Started only in 2006
- Now a standard package

Indetnd to bring performance and functionality improvements


- Efficiently store n-d arrays in vectorised form to benifit from DRAM locality
- Enable easy file save and load of n-d arrays
- Efficiently process data without type-checking overhead
- Enable other packages to use numpy arrays as an efficient data interface
- Efficiently broadcast operations across dimensions
- Provided implementations of many functions across linear algebra, statistics


## What we will focus on

1. What are n-d arrays
2. What is broadcasting
3. How to load and save n-d arrays
4. How to use statistical functions

## Comparing performance with lists, etc.

In [30]:
N = 100000000

In [31]:
%%time
list_= list(range(N))
for i in range(N):
    list_[i] = list_[i] **2

CPU times: user 41.3 s, sys: 3.54 s, total: 44.8 s
Wall time: 45 s


In [32]:
%%time
list_ = list(range(N))
list_ = [item*item for item in list_]

CPU times: user 10.4 s, sys: 6.22 s, total: 16.6 s
Wall time: 16.6 s


In [33]:
%%time
list_ = list(range(N))
list_ = map(lambda x: x*x,list_)

CPU times: user 1.55 s, sys: 2.25 s, total: 3.8 s
Wall time: 3.8 s


- `map` function performance improved significianlty

In [34]:
%%time
list_ = list(range(N))
list_sum = 0
for item in list_:
    list_sum +=item

CPU times: user 14.1 s, sys: 2.28 s, total: 16.4 s
Wall time: 16.4 s


In [35]:
%%time
list_ = list(range(N))
list_sum = sum(list_)

CPU times: user 2.36 s, sys: 1.95 s, total: 4.31 s
Wall time: 4.3 s


In [36]:
import numpy as np

In [37]:
%%time
arr = np.arange(N)
arr = arr * arr

CPU times: user 461 ms, sys: 914 µs, total: 462 ms
Wall time: 466 ms


In [38]:
%%time
arr = np.arange(N)
arr_sum = np.sum(arr)

CPU times: user 300 ms, sys: 35.6 ms, total: 336 ms
Wall time: 336 ms


## Arrays

- 1-D array : time series data
- 2-D array : Spatial data
- 3-D array : Spatial data across multiple times

1. dimension 2: Along the first axis (Columns)
2. dimension 1: Along the row axis
3. dimension 0: Last dimension we added

- So we have a 3d array of size 2 x 3 x 4

- on dimension 0, we have two possibilities and on dimension 1, we have 3 possibilities

- In Numpy 2 x 3 x 4 also called as Shape of the array

`A[1,0,1]` First one should be on dimension 0, and second one dimension 1, and third one should be dimension 2


## Creating np Arrays

In [39]:
arr = np.arange(5)

In [40]:
print(arr,type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [41]:
arr = np.array([0,2,4,6,8])

In [42]:
print(arr, type(arr))

[0 2 4 6 8] <class 'numpy.ndarray'>


In [43]:
arr

array([0, 2, 4, 6, 8])

In [45]:
arr.dtype

dtype('int64')

In [46]:
arr.ndim

1

In [47]:
arr.shape

(5,)

In [48]:
arr.size

5

In [49]:
arr2d = np.array([
                  [1,2,3],
                  [4,5,6]
])

In [50]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
arr2d.ndim

2

In [53]:
arr2d.shape

(2, 3)

In [54]:
arr2d.size

6

In [57]:
arr3d = np.array([
                  [
                   [1,2,3],
                   [4,5,6]
                  ],
                  [
                  [7,8,9],
                  [10,11,12]
                  ]
])

In [58]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [59]:
arr3d.shape

(2, 2, 3)

In [61]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [62]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])