<a href="https://colab.research.google.com/github/pavanraja753/PyTorch_Learning/blob/main/Fundamentals_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Contents


1. Installation
2. Initialization
3. Accessing and modifying data
4. Pivoting data
5. Combining data
6. Math operations



## 1. Installation

Generally NumPy is pre-installed on Colab.AWS. you should first check if NumPy is available

In [2]:
# Import the Numpy
import numpy as np

np.random.seed(0)

# 2. Initialization

In [11]:
# Initailzes an empty array with size 2 x 2
empty_arr = np.empty((2,2))

print("An empty array is \n", empty_arr, "with dimension ", empty_arr.shape, "\n")

zeros_arr = np.zeros((2,3))

print("An zeros array is \n", zeros_arr, "with dimension ", zeros_arr.shape, "\n")

ones_arr = np.ones((4,2))
print("An ones array is \n", ones_arr, "with dimension ", ones_arr.shape, "\n")

tens_arr = np.full((2,2),10)
print("A filled array is \n", tens_arr, "with dimension ", tens_arr.shape, "\n")

zeros_like_arr = np.zeros_like(ones_arr)
print("A zeros like array is \n", zeros_like_arr, "with dimension ", zeros_like_arr.shape, "\n")

full_like_arr = np.full_like(zeros_arr, 0.1, dtype=np.double)
print("A full like array is \n", full_like_arr, "with dimension ", full_like_arr.shape, "\n")





An empty array is 
 [[5.e-323 5.e-323]
 [5.e-323 5.e-323]] with dimension  (2, 2) 

An zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]] with dimension  (2, 3) 

An ones array is 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] with dimension  (4, 2) 

A filled array is 
 [[10 10]
 [10 10]] with dimension  (2, 2) 

A zeros like array is 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] with dimension  (4, 2) 

A full like array is 
 [[0.1 0.1 0.1]
 [0.1 0.1 0.1]] with dimension  (2, 3) 



###b. Create an array from existing data

In [12]:
# initialize an array with the given list

new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print("An array from given list is \n", arr_from_list, "with dimensions", arr_from_list.shape, "\n")

An array from given list is 
 [1 2 3 4] with dimensions (4,) 



In [ ]:
# initialized an arrat by loading data from a txt file
txt_arr = np.loadtxt(path_to_txt_file)

# initialize an array by loading data from a npy file
loaded_arr = np.load(path_to_npy_file)


###c. Numerical ranges

In [15]:
# return evenly spaced values within a given interval
range_arr = np.arange(10)
print("An array given range is \n", range_arr, "with dimensions", range_arr.shape, "\n")

# return evenly spaced numbers over a specified interval
linspace_arr = np.linspace(2.0,3.0,num=5, endpoint=True)
print("An evenly space array given range is \n", linspace_arr, "with dimensions", linspace_arr.shape, "\n")


An array given range is 
 [0 1 2 3 4 5 6 7 8 9] with dimensions (10,) 

An evenly space array given range is 
 [2.   2.25 2.5  2.75 3.  ] with dimensions (5,) 



###d. Create an array with random values

In [19]:
uniform_rand_arr = np.random.rand(3,2)
print("An random array given range is \n", uniform_rand_arr, "with dimensions", uniform_rand_arr.shape, "\n")

range_rand_int_arr = np.random.randint(5,size=(2,4))
print(range_rand_int_arr)

mu =3
sigma = 2.5
sample_norm_arr = mu + sigma*np.random.randn(2,4)

print(sample_norm_arr)

An random array given range is 
 [[0.83261985 0.77815675]
 [0.87001215 0.97861834]
 [0.79915856 0.46147936]] with dimensions (3, 2) 

[[3 3 0 1]
 [1 1 0 2]]
[[-0.90874173  1.58325595  2.39462621  6.78597821]
 [ 2.1673565   3.11841204  6.65685112  6.83757282]]


[[0 1 1 0]
 [1 4 3 0]]


# 3. Accessing and modifying data

###a. Indexing: Accessing values from Numpy Arrays

In [ ]:
n = np.random.randn(4,5,6) # see this a 4 batches, each containing 5 rows and 6 columns
n

In [23]:
n[1,2,3] # return values in the fourth column of 3 rd row of the 2nd batch

-1.0322430367309077

###b. Slicing

In [24]:
# slice along a batch
print(n[0,:,:]) # same as: n[0] 

[[ 1.19732198  1.88335386  0.71422382  2.28433335  1.56410258  0.61110371]
 [-0.87736332 -1.6210875  -0.581673   -0.53783395 -1.55602368 -0.05446484]
 [-1.81127879 -0.63117522 -0.92815918  1.49072192  0.19549934 -0.47160433]
 [ 1.81235465 -2.29413748  0.65120935 -1.13049645 -0.77734666  1.11593845]
 [ 1.33945302 -1.76743365  0.42441246  1.08930905 -0.38418568  0.63220141]]


In [25]:
print(n[0,0:3,0:4])

[[ 1.19732198  1.88335386  0.71422382  2.28433335]
 [-0.87736332 -1.6210875  -0.581673   -0.53783395]
 [-1.81127879 -0.63117522 -0.92815918  1.49072192]]


In [26]:
# slice along multiple batch 
print(n[:,3,4])

[-0.77734666 -2.21836076  0.22858201 -0.72805772]


### Slicing at Interval

In [ ]:
print(n[0::2])

###c. Modifying Numpy Arrays

In [30]:
n_copy = np.copy(n)

### Modify single values

In [31]:
print(n_copy[2,4,1] ==n[2,4,1])

n_copy[2,4,1] =0.005

print(n_copy[2,4,1] ==n[2,4,1])



True
False


### Modifying multiple values


In [32]:
# check if values in the two arrays are the same before copy
print(f"Are the arrays the same before modification: {n_copy[2, 3] == n[2, 3]}")
print(f"Before modifying values: {n_copy[2, 3]}")

n_copy[2, 3] = 0.5

print(f"After modifying values: {n_copy[2, 3]}")

# check if values in the two arrays are the same after copy
print(f"Are the arrays the same after modification: {n_copy[2, 3] == n[2, 3]}")

Are the arrays the same before modification: [ True  True  True  True  True  True]
Before modifying values: [-0.42389623 -3.51476812 -1.34315673  1.42550613  0.22858201 -0.25766376]
After modifying values: [0.5 0.5 0.5 0.5 0.5 0.5]
Are the arrays the same after modification: [False False False False False False]
