<a href="https://colab.research.google.com/github/pavanraja753/PyTorch_Learning/blob/main/Fundamentals_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Contents


1. Installation
2. Initialization
3. Accessing and modifying data
4. Pivoting data
5. Combining data
6. Math operations



## 1. Installation

Generally NumPy is pre-installed on Colab.AWS. you should first check if NumPy is available

In [2]:
# Import the Numpy
import numpy as np

np.random.seed(0)

# 2. Initialization

In [11]:
# Initailzes an empty array with size 2 x 2
empty_arr = np.empty((2,2))

print("An empty array is \n", empty_arr, "with dimension ", empty_arr.shape, "\n")

zeros_arr = np.zeros((2,3))

print("An zeros array is \n", zeros_arr, "with dimension ", zeros_arr.shape, "\n")

ones_arr = np.ones((4,2))
print("An ones array is \n", ones_arr, "with dimension ", ones_arr.shape, "\n")

tens_arr = np.full((2,2),10)
print("A filled array is \n", tens_arr, "with dimension ", tens_arr.shape, "\n")

zeros_like_arr = np.zeros_like(ones_arr)
print("A zeros like array is \n", zeros_like_arr, "with dimension ", zeros_like_arr.shape, "\n")

full_like_arr = np.full_like(zeros_arr, 0.1, dtype=np.double)
print("A full like array is \n", full_like_arr, "with dimension ", full_like_arr.shape, "\n")





An empty array is 
 [[5.e-323 5.e-323]
 [5.e-323 5.e-323]] with dimension  (2, 2) 

An zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]] with dimension  (2, 3) 

An ones array is 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] with dimension  (4, 2) 

A filled array is 
 [[10 10]
 [10 10]] with dimension  (2, 2) 

A zeros like array is 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] with dimension  (4, 2) 

A full like array is 
 [[0.1 0.1 0.1]
 [0.1 0.1 0.1]] with dimension  (2, 3) 



###b. Create an array from existing data

In [12]:
# initialize an array with the given list

new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print("An array from given list is \n", arr_from_list, "with dimensions", arr_from_list.shape, "\n")

An array from given list is 
 [1 2 3 4] with dimensions (4,) 



In [ ]:
# initialized an arrat by loading data from a txt file
txt_arr = np.loadtxt(path_to_txt_file)

# initialize an array by loading data from a npy file
loaded_arr = np.load(path_to_npy_file)


###c. Numerical ranges

In [15]:
# return evenly spaced values within a given interval
range_arr = np.arange(10)
print("An array given range is \n", range_arr, "with dimensions", range_arr.shape, "\n")

# return evenly spaced numbers over a specified interval
linspace_arr = np.linspace(2.0,3.0,num=5, endpoint=True)
print("An evenly space array given range is \n", linspace_arr, "with dimensions", linspace_arr.shape, "\n")


An array given range is 
 [0 1 2 3 4 5 6 7 8 9] with dimensions (10,) 

An evenly space array given range is 
 [2.   2.25 2.5  2.75 3.  ] with dimensions (5,) 



###d. Create an array with random values

In [19]:
uniform_rand_arr = np.random.rand(3,2)
print("An random array given range is \n", uniform_rand_arr, "with dimensions", uniform_rand_arr.shape, "\n")

range_rand_int_arr = np.random.randint(5,size=(2,4))
print(range_rand_int_arr)

mu =3
sigma = 2.5
sample_norm_arr = mu + sigma*np.random.randn(2,4)

print(sample_norm_arr)

An random array given range is 
 [[0.83261985 0.77815675]
 [0.87001215 0.97861834]
 [0.79915856 0.46147936]] with dimensions (3, 2) 

[[3 3 0 1]
 [1 1 0 2]]
[[-0.90874173  1.58325595  2.39462621  6.78597821]
 [ 2.1673565   3.11841204  6.65685112  6.83757282]]


[[0 1 1 0]
 [1 4 3 0]]


# 3. Accessing and modifying data

###a. Indexing: Accessing values from Numpy Arrays

In [ ]:
n = np.random.randn(4,5,6) # see this a 4 batches, each containing 5 rows and 6 columns
n

In [23]:
n[1,2,3] # return values in the fourth column of 3 rd row of the 2nd batch

-1.0322430367309077

###b. Slicing

In [24]:
# slice along a batch
print(n[0,:,:]) # same as: n[0] 

[[ 1.19732198  1.88335386  0.71422382  2.28433335  1.56410258  0.61110371]
 [-0.87736332 -1.6210875  -0.581673   -0.53783395 -1.55602368 -0.05446484]
 [-1.81127879 -0.63117522 -0.92815918  1.49072192  0.19549934 -0.47160433]
 [ 1.81235465 -2.29413748  0.65120935 -1.13049645 -0.77734666  1.11593845]
 [ 1.33945302 -1.76743365  0.42441246  1.08930905 -0.38418568  0.63220141]]


In [25]:
print(n[0,0:3,0:4])

[[ 1.19732198  1.88335386  0.71422382  2.28433335]
 [-0.87736332 -1.6210875  -0.581673   -0.53783395]
 [-1.81127879 -0.63117522 -0.92815918  1.49072192]]


In [26]:
# slice along multiple batch 
print(n[:,3,4])

[-0.77734666 -2.21836076  0.22858201 -0.72805772]


### Slicing at Interval

In [ ]:
print(n[0::2])

###c. Modifying Numpy Arrays

In [30]:
n_copy = np.copy(n)

### Modify single values

In [31]:
print(n_copy[2,4,1] ==n[2,4,1])

n_copy[2,4,1] =0.005

print(n_copy[2,4,1] ==n[2,4,1])



True
False


### Modifying multiple values


In [32]:
# check if values in the two arrays are the same before copy
print(f"Are the arrays the same before modification: {n_copy[2, 3] == n[2, 3]}")
print(f"Before modifying values: {n_copy[2, 3]}")

n_copy[2, 3] = 0.5

print(f"After modifying values: {n_copy[2, 3]}")

# check if values in the two arrays are the same after copy
print(f"Are the arrays the same after modification: {n_copy[2, 3] == n[2, 3]}")

Are the arrays the same before modification: [ True  True  True  True  True  True]
Before modifying values: [-0.42389623 -3.51476812 -1.34315673  1.42550613  0.22858201 -0.25766376]
After modifying values: [0.5 0.5 0.5 0.5 0.5 0.5]
Are the arrays the same after modification: [False False False False False False]


# 4. Pivoting data

##a. Reshaping Arrays

Array reshaping is an operation that changes the shape of an arrat whilst maintainign the same data in the array.

For instance, reshaping from (3,4,5) -> (2,5,6) or from (3,4,5) -> (6,10). A reshape operation is valid, as long as the product of new shape specified matched the product of the old shape

#### Reshaping within the same number of dimensions

In [33]:
s= np.random.rand(3, 4, 5)
print(f"Original Shape:{s.shape}")

Original Shape:(3, 4, 5)


In [36]:
s.size
print(s)

[[[0.0446123  0.79979588 0.07695645 0.51883515 0.3068101 ]
  [0.57754295 0.95943334 0.64557024 0.03536244 0.43040244]
  [0.51001685 0.53617749 0.68139251 0.2775961  0.12886057]
  [0.39267568 0.95640572 0.18713089 0.90398395 0.54380595]]

 [[0.45691142 0.88204141 0.45860396 0.72416764 0.39902532]
  [0.90404439 0.69002502 0.69962205 0.3277204  0.75677864]
  [0.63606106 0.24002027 0.16053882 0.79639147 0.9591666 ]
  [0.45813883 0.59098417 0.85772264 0.45722345 0.95187448]]

 [[0.57575116 0.82076712 0.90884372 0.81552382 0.15941446]
  [0.62889844 0.39843426 0.06271295 0.42403225 0.25868407]
  [0.84903831 0.03330463 0.95898272 0.35536885 0.35670689]
  [0.0163285  0.18523233 0.4012595  0.92929142 0.09961493]]]


In [38]:
s1= s.reshape(2,6,5)
print(f"Reshaped from s:{s1.shape}")
print(s1)

Reshaped from s:(2, 6, 5)
[[[0.0446123  0.79979588 0.07695645 0.51883515 0.3068101 ]
  [0.57754295 0.95943334 0.64557024 0.03536244 0.43040244]
  [0.51001685 0.53617749 0.68139251 0.2775961  0.12886057]
  [0.39267568 0.95640572 0.18713089 0.90398395 0.54380595]
  [0.45691142 0.88204141 0.45860396 0.72416764 0.39902532]
  [0.90404439 0.69002502 0.69962205 0.3277204  0.75677864]]

 [[0.63606106 0.24002027 0.16053882 0.79639147 0.9591666 ]
  [0.45813883 0.59098417 0.85772264 0.45722345 0.95187448]
  [0.57575116 0.82076712 0.90884372 0.81552382 0.15941446]
  [0.62889844 0.39843426 0.06271295 0.42403225 0.25868407]
  [0.84903831 0.03330463 0.95898272 0.35536885 0.35670689]
  [0.0163285  0.18523233 0.4012595  0.92929142 0.09961493]]]


### Reshaping to a different number of dimensiona

In [40]:
r= np.arange(120)
print(f"Original shape: {r.shape}")

Original shape: (120,)


In [41]:
# (120,) -> (3, 4, 10)
r1 = r.reshape(3,4,10)
print(f"Reshape from r: {r1.shape}")

Reshape from r: (3, 4, 10)


In [42]:
print(r1)

[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]]

 [[ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]]

 [[ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]]]


In [43]:
#(3, 4, 10) -> (6, 20)
r2 = r1.reshape(6,20)

In [44]:
print(r2.shape)

(6, 20)


###b. Transposing Arrays

In [45]:
w = np.arange(90).reshape([3,5,6])
w

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89]]])

### Transpose witout speciying axes

In [47]:
w1 = np.transpose(w)
print(w1.shape)

(6, 5, 3)


### Transpose with axes

In [49]:
w2 = np.transpose(w, axes=(0,2,1))
print(w2)
print(w.shape)
print(w2.shape)

[[[ 0  6 12 18 24]
  [ 1  7 13 19 25]
  [ 2  8 14 20 26]
  [ 3  9 15 21 27]
  [ 4 10 16 22 28]
  [ 5 11 17 23 29]]

 [[30 36 42 48 54]
  [31 37 43 49 55]
  [32 38 44 50 56]
  [33 39 45 51 57]
  [34 40 46 52 58]
  [35 41 47 53 59]]

 [[60 66 72 78 84]
  [61 67 73 79 85]
  [62 68 74 80 86]
  [63 69 75 81 87]
  [64 70 76 82 88]
  [65 71 77 83 89]]]
(3, 5, 6)
(3, 6, 5)


In [ ]:
w3 = np.transpose(w,axes =(1, 2, 0))
print(w3.shape)
print(w3)

###c. Flattening Arrays

the flatten operation in Numpy collapses arrays of multiple dimensions into one dimension

Different orders can be specified when flattenign Numpy Arrays. See examples below

In [52]:
k = np.random.rand(5,6)
k

array([[0.66585912, 0.51730852, 0.42408899, 0.55468781, 0.28705152,
        0.70657471],
       [0.41485687, 0.36054556, 0.82865691, 0.92496691, 0.04600731,
        0.23262699],
       [0.34851937, 0.81496648, 0.98549143, 0.9689717 , 0.90494835,
        0.29655627],
       [0.99201124, 0.24942004, 0.10590615, 0.95095261, 0.23342026,
        0.68976827],
       [0.05835636, 0.7307091 , 0.88172021, 0.2724369 , 0.3790569 ,
        0.37429618]])

### Flattening Arrays alon the row(default order)

In [53]:
k.flatten() # all rows are stacked on each other into a 1D array

array([0.66585912, 0.51730852, 0.42408899, 0.55468781, 0.28705152,
       0.70657471, 0.41485687, 0.36054556, 0.82865691, 0.92496691,
       0.04600731, 0.23262699, 0.34851937, 0.81496648, 0.98549143,
       0.9689717 , 0.90494835, 0.29655627, 0.99201124, 0.24942004,
       0.10590615, 0.95095261, 0.23342026, 0.68976827, 0.05835636,
       0.7307091 , 0.88172021, 0.2724369 , 0.3790569 , 0.37429618])

In [56]:
k.flatten().shape

(30,)

### Flattening Arrays along the column


In [57]:
k.flatten('F') # forms a 1D array where elements in a column are listed before movinf to the next columns

array([0.66585912, 0.41485687, 0.34851937, 0.99201124, 0.05835636,
       0.51730852, 0.36054556, 0.81496648, 0.24942004, 0.7307091 ,
       0.42408899, 0.82865691, 0.98549143, 0.10590615, 0.88172021,
       0.55468781, 0.92496691, 0.9689717 , 0.95095261, 0.2724369 ,
       0.28705152, 0.04600731, 0.90494835, 0.23342026, 0.3790569 ,
       0.70657471, 0.23262699, 0.29655627, 0.68976827, 0.37429618])

### Flattening Arrays using Ravel

In [58]:
k.ravel() # ravel is another way compared to flatten

array([0.66585912, 0.51730852, 0.42408899, 0.55468781, 0.28705152,
       0.70657471, 0.41485687, 0.36054556, 0.82865691, 0.92496691,
       0.04600731, 0.23262699, 0.34851937, 0.81496648, 0.98549143,
       0.9689717 , 0.90494835, 0.29655627, 0.99201124, 0.24942004,
       0.10590615, 0.95095261, 0.23342026, 0.68976827, 0.05835636,
       0.7307091 , 0.88172021, 0.2724369 , 0.3790569 , 0.37429618])

In [59]:
k.ravel('F')

array([0.66585912, 0.41485687, 0.34851937, 0.99201124, 0.05835636,
       0.51730852, 0.36054556, 0.81496648, 0.24942004, 0.7307091 ,
       0.42408899, 0.82865691, 0.98549143, 0.10590615, 0.88172021,
       0.55468781, 0.92496691, 0.9689717 , 0.95095261, 0.2724369 ,
       0.28705152, 0.04600731, 0.90494835, 0.23342026, 0.3790569 ,
       0.70657471, 0.23262699, 0.29655627, 0.68976827, 0.37429618])

### Flattening Array using Numpy Reshape

In [63]:
k.reshape(-1)

array([0.66585912, 0.51730852, 0.42408899, 0.55468781, 0.28705152,
       0.70657471, 0.41485687, 0.36054556, 0.82865691, 0.92496691,
       0.04600731, 0.23262699, 0.34851937, 0.81496648, 0.98549143,
       0.9689717 , 0.90494835, 0.29655627, 0.99201124, 0.24942004,
       0.10590615, 0.95095261, 0.23342026, 0.68976827, 0.05835636,
       0.7307091 , 0.88172021, 0.2724369 , 0.3790569 , 0.37429618])

### Flatten vs Ravel

In [64]:
test = np.random.rand(4,5)

In [65]:
test_flatten = test.flatten()
test_ravel = test.ravel()

print(test_flatten)
print(test_ravel)

[0.74878826 0.23780724 0.1718531  0.44929165 0.30446841 0.83918912
 0.23774183 0.50238946 0.9425836  0.6339977  0.86728941 0.94020969
 0.75076486 0.69957506 0.96796557 0.99440079 0.45182168 0.07086978
 0.29279403 0.15235471]
[0.74878826 0.23780724 0.1718531  0.44929165 0.30446841 0.83918912
 0.23774183 0.50238946 0.9425836  0.6339977  0.86728941 0.94020969
 0.75076486 0.69957506 0.96796557 0.99440079 0.45182168 0.07086978
 0.29279403 0.15235471]


In [67]:
test_flatten[0] = 5
print(test_flatten)
print(test)

[5.         0.23780724 0.1718531  0.44929165 0.30446841 0.83918912
 0.23774183 0.50238946 0.9425836  0.6339977  0.86728941 0.94020969
 0.75076486 0.69957506 0.96796557 0.99440079 0.45182168 0.07086978
 0.29279403 0.15235471]
[[0.74878826 0.23780724 0.1718531  0.44929165 0.30446841]
 [0.83918912 0.23774183 0.50238946 0.9425836  0.6339977 ]
 [0.86728941 0.94020969 0.75076486 0.69957506 0.96796557]
 [0.99440079 0.45182168 0.07086978 0.29279403 0.15235471]]


In [68]:
# Ravel uses references mechanism. So it changes the values of the test_array as well 
test_ravel[0] = 5
print(test_ravel)
print(test)

[5.         0.23780724 0.1718531  0.44929165 0.30446841 0.83918912
 0.23774183 0.50238946 0.9425836  0.6339977  0.86728941 0.94020969
 0.75076486 0.69957506 0.96796557 0.99440079 0.45182168 0.07086978
 0.29279403 0.15235471]
[[5.         0.23780724 0.1718531  0.44929165 0.30446841]
 [0.83918912 0.23774183 0.50238946 0.9425836  0.6339977 ]
 [0.86728941 0.94020969 0.75076486 0.69957506 0.96796557]
 [0.99440079 0.45182168 0.07086978 0.29279403 0.15235471]]
