<a href="https://colab.research.google.com/github/pavanraja753/PyTorch_Learning/blob/main/PyTorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torchvision
import torch

In [ ]:
from torchvision.datasets import CIFAR10
cifat = CIFAR10('./',train=True,download=True)

- In-place operations are suffixed with an underscore.
- and a 0d tensor can be converted back to a Python scalar with `item()`

In [12]:
x = torch.empty(2,5)
x.size()
x.fill_(1.125)
x.mean()
x.std()
x.sum()
x.sum().item()

11.25

`size()` returns the size / shape of the tensor and has as many components as the number of dimensions of the tensor. E.g. a tensor of size `torch.Size([2, 5])` is a matrix with two rows and five columns.

We should use `item()` when printing a single value (to a text file for instance), otherwise `tensor(...)` is printed.

The default tensor type `torch.Tensor` is an alias for `torch.FloatTensor`, but there are others with greater/lesser precision and on CPU/GPU. It can be set to a different type with `torch.set_default_tensor_type`. We will come back to this.

### For instance an element of R3 is a three-dimension vector, but a one-dimension tensor.

In [11]:
x.sum().item()

11.25

PyTorch provides operators for component-wise and vector/matrix operations

In [13]:
x = torch.tensor([10.,20.,30.])
y = torch.tensor([11.,21.,31.])

In [14]:
x + y

tensor([21., 41., 61.])

In [15]:
x * y

tensor([110., 420., 930.])

In [16]:
x**2

tensor([100., 400., 900.])

In [17]:
m = torch.tensor([[0.,0.,3.],
                  [0,2,0],
                  [1,0,0]])

m.mv(x)

tensor([90., 40., 10.])

In [18]:
m @ x

tensor([90., 40., 10.])

The `@` operator corresponds to matrix/vector or matrix/matrix multiplication, while `*` is component-wise product and can be applied to tensors of arbitrary size, in particular of dimension greater than 2

And as in `NumPy`, the `:` symbol defines a range of values for an index and allows to slice tensors.

In [19]:
import torch
x = torch.empty(2,4).random_(10)
x

tensor([[3., 5., 6., 9.],
        [1., 6., 5., 1.]])

In [20]:
x[0]

tensor([3., 5., 6., 9.])

In [21]:
x[0,:]

tensor([3., 5., 6., 9.])

In [22]:
x[:,0]

tensor([3., 1.])

In [23]:
x[:,1:3] = -1

In [24]:
x

tensor([[ 3., -1., -1.,  9.],
        [ 1., -1., -1.,  1.]])

`PyTorch` provides interfacing to standard linear operations, such as linear system solving or eigen decomposition

In [25]:
y = torch.empty(3).normal_()
y

tensor([-0.3125, -0.5410, -1.0462])

In [26]:
m = torch.empty(3,3).normal_()

In [27]:
q, _ = torch.lstsq(y,m)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: torch.lstsq is deprecated in favor of torch.linalg.lstsq and will be removed in a future PyTorch release.
torch.linalg.lstsq has reversed arguments and does not return the QR decomposition in the returned tuple (although it returns other information about the problem).
To get the qr decomposition consider using torch.linalg.qr.
The returned solution in torch.lstsq stored the residuals of the solution in the last m - n columns of the returned value whenever m > n. In torch.linalg.lstsq, the residuals in the field 'residuals' of the returned named tuple.
The unpacking of the solution, as in
X, _ = torch.lstsq(B, A).solution[:A.size(1)]
should be replaced with
X = torch.linalg.lstsq(A, B).solution (Triggered internally at  ../aten/src/ATen/native/BatchLinearAlgebra.cpp:3668.)
  """Entry point for launching an IPython kernel.


In [28]:
torch.mm(m,q)

tensor([[-0.3125],
        [-0.5410],
        [-1.0462]])

In [29]:
m @ q

tensor([[-0.3125],
        [-0.5410],
        [-1.0462]])

# 1.5. High dimension tensors

A tensor can be of several types

- `torch.float16, torch.float32, torch.float64`,
- `torch.uint8`,
- `torch.int8, torch.int16, torch.int32, torch.int64`



and can be located eighter in the CPU's or in a GPU's memory



Operations with tensors stored in a certain device’s memory are done by that device. We will come back to that later.

*All the coefficients in a given tensor are of the same type, which can be either an integer or floating point value of a certain precision.*



In [30]:
x = torch.zeros(1,3)
x.dtype, x.device

(torch.float32, device(type='cpu'))

In [31]:
x = x.long()
x.dtype, x.device

(torch.int64, device(type='cpu'))

In [ ]:
x = x.to('cuda')

- The deafault type of tensor values is `torch.float32`, and the deafualt computing device is the CPU.

- The data type od the tensor can be accesses with `dtype` and the device on which the tensor lies with `device`

- When casting a tensor to a new type (for instance here with x = x.long()), a copy is actually made. If the type is already adequate, a reference to the same tensor is returned.

- It is a best practice to define the device that is going to be used once for all at the beginning of a program, and use the method to(device) to move the data to the target device


## Higher dimensions

- A 2d tensor can be seen as a grayscale image: the first index is the row, and the second index the column.

- A 3d tensor can be viewed as a RGB image. The standard in PyTorch is to have the channel index first. For instance, a CIFAR10 image is of size `3×32×32`.

- A 4d tensor can be seen as a sequence of multi-channel images. For instance, given a minibatch `batch` of 10 CIFAR10 images is of size `10×3×32×32`,


- the 5th image can be accessed as `batch[4]`
- the blue channel (3rd) of the 7th image can be accessed with `batch[6, 2]` or `batch[6, 2, :, :]`

In [37]:
x = torch.tensor([[1,3,0],[2,4,6]])
x

tensor([[1, 3, 0],
        [2, 4, 6]])

In [38]:
x.t()
x

tensor([[1, 3, 0],
        [2, 4, 6]])

In [39]:
x.view(-1)

tensor([1, 3, 0, 2, 4, 6])

In [40]:
x

tensor([[1, 3, 0],
        [2, 4, 6]])

In [41]:
x.view(3,-1)

tensor([[1, 3],
        [0, 2],
        [4, 6]])

In [42]:
x[:,1:3]

tensor([[3, 0],
        [4, 6]])

In [43]:
x.view(1,2,3).expand(3,2,3)

tensor([[[1, 3, 0],
         [2, 4, 6]],

        [[1, 3, 0],
         [2, 4, 6]],

        [[1, 3, 0],
         [2, 4, 6]]])

 - `t()` can be applied to a 2d tensor and simply transpose the indices, as a classical matrix transpose

 - `view()` unfolds the tensor in a differnet shape. Using `-1` for one of the dimension copmuted the proper value to match the number of coefficients with the original tensor.

 - Here, `x.view(1,2,3).expand(3, 2, 3)` can also be acheived with `x.unsqueeze(0).expand(3,2,3)`

- Transposing two dimensions of a tensor can also be done by specifying the two dimensions as input: `transpose(dim0, dim1)`. This is of course applicable to tensors of greater than two dimensions

In [46]:
x = torch.tensor([
                  [[1,2,1],
                   [2,1,2]],
                  [[3,0,3],
                  [0,3,0]]
])

In [49]:
x.shape

torch.Size([2, 2, 3])

In [48]:
x[0:1,:,:]

tensor([[[1, 2, 1],
         [2, 1, 2]]])

In [50]:
x.transpose(0,1)
x.shape

torch.Size([2, 2, 3])

In [54]:
x.transpose(1,2).shape

torch.Size([2, 3, 2])

**For efficiency reasons, different tensors can share the same data and 􏰂 modifying one will modify the others. By default do not make the
assumption that two tensors refer to different data in memory.**

In [56]:
a= torch.full((2,3),1)
a

tensor([[1, 1, 1],
        [1, 1, 1]])

In [58]:
b = a.view(-1)
b

tensor([1, 1, 1, 1, 1, 1])

In [59]:
a[1,1] = 2

In [60]:
b

tensor([1, 1, 1, 1, 2, 1])

In [61]:
b[0]=9
print(b)
print(a)

tensor([9, 1, 1, 1, 2, 1])
tensor([[9, 1, 1],
        [1, 2, 1]])


Note that many operations returns a new tensor which shares the same underlying storage as the original tensor, so changing the values of one will change the other as well: `view`, `transpose`, `squeeze`, `unsqueeze`, `expand`, `permute,` etc.

##PyTorch offers simple interfaces to standard image databases

In [67]:
import torch, torchvision

cifar = torchvision.datasets.CIFAR10("./",train=True,download=True)
cifar.data.shape
x = torch.from_numpy(cifar.data).permute(0,3,1,2).float()/255.0
print(x.dtype, x.size(), x.min().item(), x.max().item())

Files already downloaded and verified
torch.float32 torch.Size([50000, 3, 32, 32]) 0.0 1.0


- Note that there are different storage conventions between some libraries used by `PyTorch` (`pillow and NumPy`) and PyTorch itself:

   

1.   loading the images yields a tensor of shape `50000×32×32×3`, but `PyTorch` works with the channel dimension as the second one: `50000×3×32×32.`

2.   This change is made with `permute(0, 3, 1, 2)` which means that we want dimension 3 of the original tensor to lie at the second position of the new tensor.

In [69]:
# Narrows to the first images, converts to float
x = x[:48]
x.shape

torch.Size([48, 3, 32, 32])

In [70]:
# saves these images as a single image
torchvision.utils.save_image(x,'cifar.png',nrow=12)

In [72]:
# Switches the row and column indexes
x = x.transpose_(3,2)
torchvision.utils.save_image(x,'cifar.png',nrow=12)

Since the data follows the standard `PyTorch` “channel first” convention, transposing
dimensions 2 and 3 (that is the 3rd and the fourth) exchanges the height and width of the images.
Remember that functions ending with an underscore operate in-place.

In [73]:
# Kills the green and blue channels
x[:,1:3].fill_(0)
torchvision.utils.save_image(x,'cifar.png',nrow=12)

## Broadcasting and Einstein summations

Broadcasting automagically expands dimensions by replicating coefficients, when it is necessary to perform operations that are “intuitively reasonable”.

In [76]:
x = torch.empty(100,4).normal_(2)
x.mean(0).shape

torch.Size([4])

In [77]:
x = x- x.mean(0)

In [78]:
x.mean(0)

tensor([ 7.7486e-08,  1.5497e-07, -1.1921e-09, -5.2452e-08])

- Broadcasting is a mechanism taken from NumPy which expands the proper dimensions of size 1 to perform operations on tensors/arrays of different dimensions.

- In the example above, considering that a `N × D` tensor is a list of `N` vectors of dimension `D`, we want to compute the mean vector. So, here, starting from a tensor of dimension `(100, 4)`, the mean along dimension `0` yields a tensor with 4 values of size `(4,)`, one for each column.

It is quite natural to substract a vector to a series of vectors. For instance here, it seems reasonable to subtract the mean vector to all the vectors of x, but since the dimensions are respectively (4,) and (100, 4), the operation cannot be done.

To allow it, the “broadcasting” mechanism creates `[implicitely]` a matrix of size (100, 4) by replicating the row 100 times.

Precisely, broadcasting proceeds as follows:

1.   If one of the tensors has fewer dimensions than the other, it is reshaped by adding as many dimensions of size 1 as necessary in the front; then

2.  for every dimension mismatch, if one of the two tensors is of size one, it is expanded along this axis by replicating coefficients.

If there is a tensor size mismatch for one of the dimension and neither of them is one, the operation fails

In [79]:
# Broadcasting example

A = torch.tensor([
                  [1.],
                  [2.],
                  [3.],
                  [4.]
])

B = torch.tensor([[5., -5., 5., -5., 5.]])

print(A.shape), print(B.shape)

torch.Size([4, 1])
torch.Size([1, 5])


(None, None)

In [80]:
print(A+B)

tensor([[ 6., -4.,  6., -4.,  6.],
        [ 7., -3.,  7., -3.,  7.],
        [ 8., -2.,  8., -2.,  8.],
        [ 9., -1.,  9., -1.,  9.]])


In the example,

- `A` is of size `(4,1)`
- `B` is of size `(1,5)`

Following the procedure of the previous slide,

Both tensors have two dimensions;

Then, for each of the two dimensions:

1.  On dimension `0`, `A` has `4` rows, while `B` has `1`. Therefore, `B` is expanded along this dimension by replicating its row `4` times. The “new” `B` is of size `(4,5)`.

2.  On dimension `1`, `A` has `1` column, while `B` has `5`. Therefore, `A` is expanded along this dimension by replicating its column `5` times. The
“new” `A` is of size `(4,5)`.

3. The operation can be perform on
these two tensors of size `(4,5)`.


Note that all this is transparent and that no copy is actually made.

# 1.6 Tensor Internals

In [82]:
x = torch.zeros(2,3)
print(x.storage())

 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
[torch.FloatStorage of size 6]


In [83]:
q = x.storage()
q[0] = 1
print(q), print(x)

 1.0
 0.0
 0.0
 0.0
 0.0
 0.0
[torch.FloatStorage of size 6]
tensor([[1., 0., 0.],
        [0., 0., 0.]])


(None, None)

In [85]:
q = torch.arange(0.0,20.0).storage()
x = torch.empty(0).set_(q, storage_offset=6,size = (3,2),stride=(4,1))

In [86]:
x

tensor([[ 6.,  7.],
        [10., 11.],
        [14., 15.]])

- The offset is the location of the first coefficient of the tensor in the storage
- The stride is the number of memory elements that should be skipped to go one element the following one in that dimension.

- On the illustration, tensor x starts at element 5 of the storage.

- We move along dimension 0 by jumping of 4 elements in memory:

### We can explicitly create different “views” of the same storage

In [87]:
n = torch.linspace(1, 4, 4)
n

tensor([1., 2., 3., 4.])

In [88]:
torch.tensor(0.).set_(n.storage(), 1, (3, 3), (0, 1))

tensor([[2., 3., 4.],
        [2., 3., 4.],
        [2., 3., 4.]])

In [89]:
torch.tensor(0.).set_(n.storage(), 1, (2, 4), (1, 0))

tensor([[2., 2., 2., 2.],
        [3., 3., 3., 3.]])

This is in particular how transpositions and broadcasting are implemented.

In [90]:
x = torch.empty(100, 100)
x.stride()

(100, 1)

In [91]:
y = x.t()
y.stride()

(1, 100)

The main idea of functions like `view`, `narrow`, `transpose`, etc. and of operations involving broadcasting is to never replicate data in memory, but to “play” with the offsets and strides of the underlying storage.

## This organization explains the following (maybe surprising) error

In [92]:
x = torch.empty(100, 100)
x.t().view(-1)

RuntimeError: ignored

`x.t()` shares `x’s` storage and cannot be “flattened” to 1d.

This can be fixed with `contiguous()`, which returns a contiguous version of the tensor,
making a copy if needed.
The function `reshape()` combines `view()`and `contiguous()`.
