<a href="https://colab.research.google.com/github/pavanraja753/PyTorch_Learning/blob/main/PyTorch_Tensors___Part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# 

device = torch.cuda.is_available()
print(device)

True


# Tensor creation

In [3]:
t1 = torch.ones(size=(5,3))
print(t1)

t2 = torch.zeros(size=(5,3))
print(t2)

t3 = torch.eye(4)
print(t3)

t4 = torch.rand(size=(3,4))
print(t4)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[0.8444, 0.8931, 0.5763, 0.5827],
        [0.0963, 0.0121, 0.6119, 0.5915],
        [0.5880, 0.2537, 0.8527, 0.3123]])


# Creating tensors from existing data

In [4]:
import numpy as np

t1 = torch.tensor([1,2,3,4])  # creating from a Python list
print(t1.shape)

t2 = torch.tensor([[1],[2],[3],[4]])  # creating from a Python list
print(t2.shape)
t2 = torch.tensor(np.array([1,2,3,4])) # creating for a Numpy arrray

t3 = t2.clone()  # cloning for a existing tensor
print(t3)

torch.Size([4])
torch.Size([4, 1])
tensor([1, 2, 3, 4])


# Tensor conversion

In [5]:
# create a numpy array
np_array = np.array([1,2,3,4])
print(np_array)
print(type(np_array), np_array.dtype)

# from numpy array
torch_tensor = torch.from_numpy(np_array)
print(torch_tensor)
print(type(torch_tensor), torch_tensor.dtype)


# Changing datatype of torch tensor
print(torch_tensor.float(),torch_tensor.float().dtype)
print(torch_tensor.double())

# In case if you pushed to CUDA use torch.cuda.DoubleTensor()

[1 2 3 4]
<class 'numpy.ndarray'> int64
tensor([1, 2, 3, 4])
<class 'torch.Tensor'> torch.int64
tensor([1., 2., 3., 4.]) torch.float32
tensor([1., 2., 3., 4.], dtype=torch.float64)


In [6]:
# convert tensor to a numpy array

t1 = torch.tensor([1,2,3,4])
print(t1)
t1 = t1.detach().numpy()
print(t1.dtype)

tensor([1, 2, 3, 4])
int64


# Pushing the Data to the Device

In [8]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
t1 = torch.tensor(t1)
# pushing tesnort to the device
t1 = t1.to(device)

cuda


# Tensor Indexing

In [11]:
# Basic
t = torch.rand(size=(3,4,5))  # 3D tensor

print('Original Tensor t:')
print(t)
print('\n')

# some ways of accessing element of a tensor

print('t[0][0][0]\n', t[0][0][0])
print('t[1,2,3]\n', t[1,2,3])
print('t[-1,-1][-1]',t[-1,-1][-1])


Original Tensor t:
tensor([[[0.9018, 0.2825, 0.5923, 0.3527, 0.4381],
         [0.2255, 0.0499, 0.9788, 0.8467, 0.9255],
         [0.8004, 0.0746, 0.5842, 0.5955, 0.9045],
         [0.3769, 0.7529, 0.6797, 0.7735, 0.7761]],

        [[0.2528, 0.7297, 0.3520, 0.2985, 0.8000],
         [0.9105, 0.1512, 0.3752, 0.3066, 0.7762],
         [0.3387, 0.3875, 0.1329, 0.6678, 0.1088],
         [0.0272, 0.7467, 0.3765, 0.7073, 0.1672]],

        [[0.4470, 0.7320, 0.2334, 0.0687, 0.8031],
         [0.7911, 0.8700, 0.9020, 0.8947, 0.4526],
         [0.0800, 0.9231, 0.4980, 0.3901, 0.0589],
         [0.5293, 0.3215, 0.7646, 0.5023, 0.7999]]])


t[0][0][0]
 tensor(0.9018)
t[1,2,3]
 tensor(0.6678)
t[-1,-1][-1] tensor(0.7999)


# Tensor Slicing

In [13]:
print('Original Tensor t:')
print(t)
print('\n')

print('t[0]\n',t[0])
print('t[:1]\n',t[:1])
print('t[:,1]\n',t[:,1])
print('t[:,:,3]',t[:,:,3])

Original Tensor t:
tensor([[[0.9018, 0.2825, 0.5923, 0.3527, 0.4381],
         [0.2255, 0.0499, 0.9788, 0.8467, 0.9255],
         [0.8004, 0.0746, 0.5842, 0.5955, 0.9045],
         [0.3769, 0.7529, 0.6797, 0.7735, 0.7761]],

        [[0.2528, 0.7297, 0.3520, 0.2985, 0.8000],
         [0.9105, 0.1512, 0.3752, 0.3066, 0.7762],
         [0.3387, 0.3875, 0.1329, 0.6678, 0.1088],
         [0.0272, 0.7467, 0.3765, 0.7073, 0.1672]],

        [[0.4470, 0.7320, 0.2334, 0.0687, 0.8031],
         [0.7911, 0.8700, 0.9020, 0.8947, 0.4526],
         [0.0800, 0.9231, 0.4980, 0.3901, 0.0589],
         [0.5293, 0.3215, 0.7646, 0.5023, 0.7999]]])


t[0]
 tensor([[0.9018, 0.2825, 0.5923, 0.3527, 0.4381],
        [0.2255, 0.0499, 0.9788, 0.8467, 0.9255],
        [0.8004, 0.0746, 0.5842, 0.5955, 0.9045],
        [0.3769, 0.7529, 0.6797, 0.7735, 0.7761]])
t[:1]
 tensor([[[0.9018, 0.2825, 0.5923, 0.3527, 0.4381],
         [0.2255, 0.0499, 0.9788, 0.8467, 0.9255],
         [0.8004, 0.0746, 0.5842, 0.5955, 0.9

# Pivoting and Reshaping

1. Flatten
2. Squeeze
3. Reshape
4. View
5. Transpose
6. Permute

1. Flatten: Changes the multi-dimensional tensor into a single dimension

In [16]:
t = torch.randn(size=(3,4,5))   # 3D Tensor
print(t)
print(t.shape)
print(t.flatten(1,2))
print(t.flatten().shape)

tensor([[[-0.2295, -1.5913, -0.9388, -0.0113,  0.2115],
         [-0.8163, -0.9424,  0.6183,  0.2151,  0.9767],
         [ 0.1886, -0.0236, -0.8667,  0.0425, -1.6082],
         [-0.1309,  0.7314,  0.4466, -0.8799, -0.8885]],

        [[ 1.6413,  0.0056,  2.2351, -0.5931,  0.3980],
         [ 0.7614, -0.2289,  0.8537, -0.7683,  0.6828],
         [-0.6399, -0.9252,  1.4009,  1.0028,  0.4555],
         [-0.4120, -0.2248,  0.3837, -2.5895,  0.4375]],

        [[ 0.0888, -1.9100, -1.4716, -1.5500,  0.9803],
         [ 0.0748,  0.0696,  0.0161,  0.9203,  1.1715],
         [-2.7649, -1.2428,  0.0556,  2.0267,  0.3741],
         [ 0.5431,  2.0843, -0.7382, -0.3763, -0.1481]]])
torch.Size([3, 4, 5])
tensor([[-0.2295, -1.5913, -0.9388, -0.0113,  0.2115, -0.8163, -0.9424,  0.6183,
          0.2151,  0.9767,  0.1886, -0.0236, -0.8667,  0.0425, -1.6082, -0.1309,
          0.7314,  0.4466, -0.8799, -0.8885],
        [ 1.6413,  0.0056,  2.2351, -0.5931,  0.3980,  0.7614, -0.2289,  0.8537,
         -0

# Squeeeze and Unsqueeze: To add or remove a dimension in tensor

In [18]:
t = torch.rand(size=(3,4,5))
ts = t.unsqueeze(dim=0)   # Unsqueeze alon the dimension 0
ts2 = t.unsqueeze(dim=1)  # Unsqueeze alon the dimension 1

print(ts)
print('original tensor shape',t.shape)
print('Unsqueeze along the dimension 0',ts.shape)
print('Unsqueeze along the dimension 1',ts2.shape)

tensor([[[[0.6525, 0.7022, 0.8698, 0.4752, 0.9497],
          [0.5228, 0.3384, 0.1751, 0.6933, 0.8479],
          [0.2868, 0.7380, 0.6363, 0.4254, 0.5094],
          [0.4419, 0.4000, 0.1153, 0.3401, 0.1586]],

         [[0.6131, 0.5780, 0.2181, 0.7380, 0.3282],
          [0.3327, 0.5607, 0.8984, 0.0507, 0.9977],
          [0.3424, 0.1674, 0.1644, 0.6131, 0.1852],
          [0.6609, 0.7541, 0.2911, 0.0954, 0.8175]],

         [[0.6636, 0.1768, 0.7067, 0.8382, 0.8208],
          [0.1966, 0.5817, 0.7261, 0.2586, 0.4015],
          [0.3789, 0.0240, 0.1021, 0.5406, 0.4957],
          [0.6060, 0.1787, 0.5448, 0.9549, 0.6101]]]])
original tensor shape torch.Size([3, 4, 5])
Unsqueeze along the dimension 0 torch.Size([1, 3, 4, 5])
Unsqueeze along the dimension 1 torch.Size([3, 1, 4, 5])


# Squeeze Tensor

Removes empty dimensions from a tensor

In [21]:
print(ts.squeeze(0))
print('ts.squeeze(0).shape',ts.squeeze(0).shape)

print(ts2.squeeze(1))
print('ts2.squeeze(1).shape',ts2.squeeze(1).shape)

tensor([[[0.6525, 0.7022, 0.8698, 0.4752, 0.9497],
         [0.5228, 0.3384, 0.1751, 0.6933, 0.8479],
         [0.2868, 0.7380, 0.6363, 0.4254, 0.5094],
         [0.4419, 0.4000, 0.1153, 0.3401, 0.1586]],

        [[0.6131, 0.5780, 0.2181, 0.7380, 0.3282],
         [0.3327, 0.5607, 0.8984, 0.0507, 0.9977],
         [0.3424, 0.1674, 0.1644, 0.6131, 0.1852],
         [0.6609, 0.7541, 0.2911, 0.0954, 0.8175]],

        [[0.6636, 0.1768, 0.7067, 0.8382, 0.8208],
         [0.1966, 0.5817, 0.7261, 0.2586, 0.4015],
         [0.3789, 0.0240, 0.1021, 0.5406, 0.4957],
         [0.6060, 0.1787, 0.5448, 0.9549, 0.6101]]])
ts.squeeze(0).shape torch.Size([3, 4, 5])
tensor([[[0.6525, 0.7022, 0.8698, 0.4752, 0.9497],
         [0.5228, 0.3384, 0.1751, 0.6933, 0.8479],
         [0.2868, 0.7380, 0.6363, 0.4254, 0.5094],
         [0.4419, 0.4000, 0.1153, 0.3401, 0.1586]],

        [[0.6131, 0.5780, 0.2181, 0.7380, 0.3282],
         [0.3327, 0.5607, 0.8984, 0.0507, 0.9977],
         [0.3424, 0.1674, 0.1644

# Reshpe function

Changes the shape of a tensor

In [26]:
print('Original tensor shape',t.shape)
print(t.reshape((12,5)),t.reshape(12,5).shape)
print(t.reshape((12,-1)),t.reshape(12,-1).shape)

print(t.reshape((5,4,3)),t.reshape(5,4,3).shape)

print(t.reshape((-1)),t.reshape(-1).shape)

Original tensor shape torch.Size([3, 4, 5])
tensor([[0.6525, 0.7022, 0.8698, 0.4752, 0.9497],
        [0.5228, 0.3384, 0.1751, 0.6933, 0.8479],
        [0.2868, 0.7380, 0.6363, 0.4254, 0.5094],
        [0.4419, 0.4000, 0.1153, 0.3401, 0.1586],
        [0.6131, 0.5780, 0.2181, 0.7380, 0.3282],
        [0.3327, 0.5607, 0.8984, 0.0507, 0.9977],
        [0.3424, 0.1674, 0.1644, 0.6131, 0.1852],
        [0.6609, 0.7541, 0.2911, 0.0954, 0.8175],
        [0.6636, 0.1768, 0.7067, 0.8382, 0.8208],
        [0.1966, 0.5817, 0.7261, 0.2586, 0.4015],
        [0.3789, 0.0240, 0.1021, 0.5406, 0.4957],
        [0.6060, 0.1787, 0.5448, 0.9549, 0.6101]]) torch.Size([12, 5])
tensor([[0.6525, 0.7022, 0.8698, 0.4752, 0.9497],
        [0.5228, 0.3384, 0.1751, 0.6933, 0.8479],
        [0.2868, 0.7380, 0.6363, 0.4254, 0.5094],
        [0.4419, 0.4000, 0.1153, 0.3401, 0.1586],
        [0.6131, 0.5780, 0.2181, 0.7380, 0.3282],
        [0.3327, 0.5607, 0.8984, 0.0507, 0.9977],
        [0.3424, 0.1674, 0.1644, 0.

# View function:

Similar to reshape function

# Transpose function

This function is a generalization of general matrix transpose

In [30]:
t = torch.rand(size=(2,3,4))
print(t.shape)
print(t)
print('\n')

print(t.transpose(0,1).shape)
print(t.transpose(0,2).shape)

torch.Size([2, 3, 4])
tensor([[[0.1748, 0.0886, 0.9741, 0.6835],
         [0.0705, 0.6374, 0.1743, 0.6882],
         [0.6738, 0.6063, 0.3248, 0.8809]],

        [[0.1757, 0.9269, 0.1621, 0.5608],
         [0.6632, 0.8344, 0.4956, 0.2656],
         [0.3466, 0.3624, 0.8436, 0.3123]]])


torch.Size([3, 2, 4])
torch.Size([4, 3, 2])


# Permute tensor

similar to transpose, transpose onle two axis

In [32]:
print(t.permute(1,0,2).shape)

torch.Size([3, 2, 4])
